[project]
name = "iasip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.49.1",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
